// <auto-generated />
using System;
using System.Collections.Generic;
using DiNet.GPipe.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiNet.GPipe.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426140229_UniqueConstraints2")]
    partial class UniqueConstraints2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DiNet.GPipe.Domain.BuildRegistry", b =>
                {
                    b.Property<string>("CommitHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Version", "DiNet.GPipe.Domain.BuildRegistry.Version#BuildVersion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("alpha")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("beta")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("release")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("CommitHash");

                    b.HasIndex("ProjectId");

                    b.ToTable("BuildRegistries");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitUrl")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.BuildRegistry", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.ProjectModel", "Project")
                        .WithMany("Builds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.ProjectModel", b =>
                {
                    b.Navigation("Builds");
                });
#pragma warning restore 612, 618
        }
    }
}
