// <auto-generated />
using System;
using System.Collections.Generic;
using DiNet.GPipe.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiNet.GPipe.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509193812_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DiNet.GPipe.Domain.BranchWatcherConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BranchWatcherConfigs");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Builds", (string)null);

                    b.HasDiscriminator<string>("BuildType").HasValue("Build");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.BuildRegistry", b =>
                {
                    b.Property<string>("CommitHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Version", "DiNet.GPipe.Domain.BuildRegistry.Version#BuildVersion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("alpha")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("beta")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("release")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("CommitHash");

                    b.HasIndex("ProjectId");

                    b.ToTable("BuildRegistries");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.CommitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BuildVersion", "DiNet.GPipe.Domain.CommitEntry.BuildVersion#BuildVersion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("alpha")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("beta")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("release")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CommitEntries");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.ProjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitUrl")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.TestEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompletedSuccessfully")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.ToTable("TestEntries");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.WatcherSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastGlobalCheck")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PollInterval")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("WatcherSettings");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.FailedBuild", b =>
                {
                    b.HasBaseType("DiNet.GPipe.Domain.Build");

                    b.Property<string>("ErrorText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasIndex("CommitId");

                    b.HasDiscriminator().HasValue("failure");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.SuccessfullBuild", b =>
                {
                    b.HasBaseType("DiNet.GPipe.Domain.Build");

                    b.Property<string>("ApkUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasIndex("CommitId");

                    b.HasDiscriminator().HasValue("success");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.BranchWatcherConfig", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.ProjectModel", null)
                        .WithMany("BranchConfigs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.BuildRegistry", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.ProjectModel", "Project")
                        .WithMany("Builds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.CommitEntry", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.ProjectModel", null)
                        .WithMany("Commits")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.TestEntry", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.CommitEntry", null)
                        .WithMany("TestEntries")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.WatcherSettings", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.ProjectModel", null)
                        .WithOne("WatcherSettings")
                        .HasForeignKey("DiNet.GPipe.Domain.WatcherSettings", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.FailedBuild", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.CommitEntry", null)
                        .WithMany("FailedBuilds")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.SuccessfullBuild", b =>
                {
                    b.HasOne("DiNet.GPipe.Domain.CommitEntry", null)
                        .WithMany("SuccessfullBuilds")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.CommitEntry", b =>
                {
                    b.Navigation("FailedBuilds");

                    b.Navigation("SuccessfullBuilds");

                    b.Navigation("TestEntries");
                });

            modelBuilder.Entity("DiNet.GPipe.Domain.ProjectModel", b =>
                {
                    b.Navigation("BranchConfigs");

                    b.Navigation("Builds");

                    b.Navigation("Commits");

                    b.Navigation("WatcherSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
